# Generated by Django 4.2.4 on 2023-08-04 21:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('resumo', models.TextField(max_length=10000000)),
                ('descricao', ckeditor.fields.RichTextField(max_length=10000000)),
                ('imagem', models.ImageField(upload_to='thumb_img')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('brasil', 'Brasil'), ('rio grande do norte', 'Rio Grande Do Norte'), ('areia branca', 'Areia Branca'), ('cultura', 'Cultura'), ('esporte', 'Esporte'), ('política', 'Politica'), ('economia', 'Economia'), ('entretenimento', 'Entretenimento')], max_length=30)),
            ],
        ),
    ]
